# Generated by Django 5.0.7 on 2024-08-20 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('team', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Player_LastFive_stats_model',
            fields=[
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='stats_api_app.player')),
                ('last_five_minutes_per_game', models.JSONField()),
                ('last_five_points_per_game', models.JSONField()),
                ('last_five_field_goals_made', models.JSONField()),
                ('last_five_field_goals_attempted', models.JSONField()),
                ('last_five_field_goal_percentage', models.JSONField()),
                ('last_five_three_points_made', models.JSONField()),
                ('last_five_three_points_attempted', models.JSONField()),
                ('last_five_three_point_percentage', models.JSONField()),
                ('last_five_free_throws_made', models.JSONField()),
                ('last_five_free_throws_attempted', models.JSONField()),
                ('last_five_free_throw_percentage', models.JSONField()),
                ('last_five_offensive_rebounds', models.JSONField()),
                ('last_five_defensive_rebounds', models.JSONField()),
                ('last_five_total_rebounds', models.JSONField()),
                ('last_five_assists', models.JSONField()),
                ('last_five_turnovers', models.JSONField()),
                ('last_five_steals', models.JSONField()),
                ('last_five_blocks', models.JSONField()),
                ('last_five_personal_fouls', models.JSONField()),
                ('last_five_fantasy_points', models.JSONField()),
                ('last_five_double_doubles', models.JSONField()),
                ('last_five_triple_doubles', models.JSONField()),
                ('last_five_plus_minus', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Player_Season_stats_model',
            fields=[
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='stats_api_app.player')),
                ('season_average_games_played', models.IntegerField()),
                ('season_average_minutes_per_game', models.FloatField()),
                ('season_average_points_per_game', models.FloatField()),
                ('season_average_field_goals_made', models.FloatField()),
                ('season_average_field_goals_attempted', models.FloatField()),
                ('season_average_field_goal_percentage', models.FloatField()),
                ('season_average_three_points_made', models.FloatField()),
                ('season_average_three_points_attempted', models.FloatField()),
                ('season_average_three_point_percentage', models.FloatField()),
                ('season_average_free_throws_made', models.FloatField()),
                ('season_average_free_throws_attempted', models.FloatField()),
                ('season_average_free_throw_percentage', models.FloatField()),
                ('season_average_offensive_rebounds', models.FloatField()),
                ('season_average_defensive_rebounds', models.FloatField()),
                ('season_average_total_rebounds', models.FloatField()),
                ('season_average_assists', models.FloatField()),
                ('season_average_turnovers', models.FloatField()),
                ('season_average_steals', models.FloatField()),
                ('season_average_blocks', models.FloatField()),
                ('season_average_personal_fouls', models.FloatField()),
                ('season_average_fantasy_points', models.FloatField()),
                ('season_average_double_doubles', models.FloatField()),
                ('season_average_triple_doubles', models.FloatField()),
                ('season_average_plus_minus', models.FloatField()),
            ],
        ),
    ]
