# Generated by Django 5.1 on 2024-09-04 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats_api_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='nbaplayer',
            table='nba_players',
        ),
        migrations.AlterModelTable(
            name='nbaplayerseasonstats',
            table='nba_player_season_stats',
        ),
        migrations.AlterModelTable(
            name='nbaplayerslast5games',
            table='nba_players_last_5_games',
        ),
    ]
